CREATE TABLESPACE SK_TOPOFFICE
LOGGING 
    DATAFILE '/opt/oracle/oradata/kafdb/SK_TOPOFFICE.DBF' SIZE 2 G  REUSE
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT  AUTO;
CREATE USER SK_TOPOFFICE  PROFILE DEFAULT 
    IDENTIFIED BY SK_TOPOFFICE DEFAULT TABLESPACE SK_TOPOFFICE 
    TEMPORARY TABLESPACE TEMP 
    QUOTA UNLIMITED 
    ON SK_TOPOFFICE 
    ACCOUNT UNLOCK;
grant exp_full_database, create session, create synonym, resource to SK_TOPOFFICE;
GRANT CREATE MATERIALIZED VIEW TO SK_TOPOFFICE;
GRANT UPDATE ANY TABLE TO SK_TOPOFFICE;
GRANT INSERT ANY TABLE TO SK_TOPOFFICE;
GRANT EXECUTE ANY PROCEDURE TO SK_TOPOFFICE;
GRANT CREATE ANY SYNONYM TO SK_TOPOFFICE;
GRANT CREATE ANY VIEW TO SK_TOPOFFICE;
GRANT SELECT ANY SEQUENCE TO SK_TOPOFFICE;
GRANT SELECT ANY TABLE TO SK_TOPOFFICE;
GRANT UNLIMITED TABLESPACE TO SK_TOPOFFICE;
GRANT ALTER SESSION TO SK_TOPOFFICE;
